#!/bin/env bash

dirs=($(find /opt -type d -name .git | grep -v "nvim" | xargs -n 1 dirname | tr "\n" " "))

for dir in "${dirs[@]}"; do
  cd "$dir" && {
    echo -n "$dir -> "
    if [[ $(git diff --stat) != '' ]]; then
      if [[ $(git remote) != '' ]]; then
        git checkout -b backup --quiet > /dev/null
        git add . > /dev/null
        git commit -m "Backup" > /dev/null
        git push -u origin backup --quiet > /dev/null
        echo "Dirty and backed up: $dir"
      else
        echo "Dirty and no remote: $dir"
      fi
    else
      echo "Clean: $dir"
    fi
    cd || echo "What?"
  }
done
