#!/bin/env bash

_setup() {
  export GIT_WORK_TREE=~/.config/nvim/plugged/$1
  export GIT_DIR=$GIT_WORK_TREE/.git/
}

_cleanup() {
  unset GIT_WORK_TREE
  unset GIT_DIR
}

fixup(){
  _setup "$1"
  branch=$(git branch | sed -n "/*/p" | awk ' { print $NF } ')
  git checkout master
  git branch -D "$branch"
  git pull
  git checkout "$branch"
  _cleanup
}

push(){
  git push
  PROJ=$(pwd | awk -NF '/' '{ print $NF }')
  [ -n "$NVIM_LISTEN_ADDRESS" ] && nvr -c "PlugUpdate $PROJ"
}

CMD=$1
shift
$CMD "$@"
