#!/bin/env bash
{
  nv-load
  NVR_CMD=false nvr -s "$@" 2> /dev/null
} || {
  args=()
  for i in "${@[@]/-*/}"
  do
    if [ ! -z "$i" ]
    then
      args+=("$i")
    fi
  done
  nvim-qt "${args[@]}"
}
