#!/bin/bash

PROJ_DIR=${PROJ_DIR:-$HOME/titans/projects}
REQ_FILES=("requirements-dev.txt" "requirements-devel.txt" "requirements.txt")
VENV_STR=.venv/bin/activate

at () {
    # Find matching target
    if [ ! -d "$PROJ_DIR/$1" ];
    then
        if [ -e "$PROJ_DIR/.projcd" ]; then
            source $PROJ_DIR/.projcd
        else
            echo "Unable to find '.projcd' alias file" >> /dev/stderr
            return -1
        fi
        [ ${map[$1]+1} ] && TGT=${map[$1]} || (echo "Alias not found" >> /dev/stderr && return -1)
    else
        TGT=$1
    fi

    # Check if target exists
    if [ ! -e "$PROJ_DIR/$TGT" ]; then; echo "Target directory not found" >> /dev/stderr && return -1; fi

    # Leave current virtualenv, if any
    if [ ! -z "$VIRTUAL_ENV" ]; then
        deactivate
    fi

    # Force directory change
    pushd $PROJ_DIR/$TGT > /dev/null

    # Try to find a requirements file on target
    for req in $REQ_FILES; do
        if [ -e "$req" ]; then
            REQ_FILE=$req
            break
        fi
    done

    # If file exists (thus a python project)
    if [ ! -z "$REQ_FILE" ]; then

        # Check if venv is there
        if [ ! -d ".venv" ]; then 
            virtualenv-2.7 .venv
            pip install -r $REQ_FILE
        fi

        # source .venv/bin/activate
        source $VENV_STR
    fi
}
