-- -- luacheck: globals vim
--
-- local lualine = require('lualine')
--
-- lualine.setup {
--   options = {
--     icons_enabled = true,
--     theme = 'auto',
--     component_separators = { left = '', right = '' },
--     section_separators = { left = '', right = '' },
--     disabled_filetypes = {},
--     always_divide_middle = true,
--   },
--   sections = {
--     lualine_a = { 'mode' },
--     lualine_b = { 'branch', 'diff', 'diagnostics' },
--     lualine_c = { 'filename', function()
--       require('lsp-progress').progress()
--     end },
--     lualine_x = { 'filetype' },
--     lualine_y = { 'progress' },
--     lualine_z = { 'location' }
--   },
--   inactive_sections = {
--     lualine_a = {},
--     lualine_b = {},
--     lualine_c = { 'filename' },
--     lualine_x = { 'location' },
--     lualine_y = {},
--     lualine_z = {}
--   },
--   tabline = {
--     lualine_a = { 'branch' },
--     lualine_b = { 'tabs' },
--     lualine_c = { 'windows' },
--     lualine_x = {},
--     lualine_y = { vim.fn.getcwd() },
--     lualine_z = {},
--   },
--   extensions = {}
-- }
--
-- vim.api.nvim_create_augroup("lualine_augroup", { clear = true })
-- vim.api.nvim_create_autocmd("User", {
--   group = "lualine_augroup",
--   pattern = "LspProgressStatusUpdated",
--   callback = lualine.refresh,
-- })
